# Site settings
title: Hey, Gul!
description: Hey, Gul!, your magic phrase to solve your development issues.
url: "https://www.hey-gul.com"

username: Hey,&nbspGul!
user_description: 
user_title: L'incantation à utiliser si vous voulez développer des nouvelles fonctionnalités, faire grandir vos pratiques de développement ou améliorer la qualité de votre produit !

# Google-analytics
google-analytics:
  id: "UA-37787733-4"

exclude: ['package.json', 'src' , 'node_modules']
